#!/usr/bin/env python3
"""Guard the generated distribution patch against lost work.

patch/vllm-moet-v0.24.0.patch is a GENERATED artifact: the diff of the
vllm fork branch (moet-v0.24.0) against the official v0.24.0 tag. It is
never edited by hand. Three times a line of work was lost by treating it
as a source file (Kimi-K2.7 -> 81c1b34, DSpark -> ad7f29a/8aff1b7,
stream-build hunks -> 8f50e57): the work lived only in the patch file,
and the next regeneration from the branch silently erased it.

Two committed fingerprints make that failure loud:

  patch/FILES.txt  - sorted list of files the patch touches. CI fails
                     when patch and list disagree IN EITHER DIRECTION, so
                     a regeneration that drops whole files cannot land
                     without an explicit, reviewable FILES.txt edit.
  patch/SOURCE.txt - the fork-branch SHA the patch was generated from.
                     Where a fork clone is available (dev boxes; CI has
                     none) the patch must be BYTE-IDENTICAL to
                     `git diff v0.24.0 <SHA>` - this catches hand edits
                     and hunk-level losses that FILES.txt cannot see -
                     and --update only moves the SHA FORWARD along the
                     branch, so a regen cannot roll back shipped work.

Regenerating the patch (the ONLY sanctioned way - see AGENTS.md):

    python3 tools/check_patch_files.py --update

regenerates the patch from the fork branch tip and rewrites both
fingerprints to match. Then REVIEW `git diff patch/`: entries VANISHING
from FILES.txt mean work exists in the patch but not on the fork branch
- merge it into the branch first; never ship the loss.

Usage: python3 tools/check_patch_files.py [--update]
Env:   VLLM_MOET_FORK=/path/to/fork/clone  (overrides discovery; the
       default locations are /workspace/vllm-v0.24.0 and
       /root/workspace/vllm-v0.24.0; byte-verify is skipped when no
       clone is found, e.g. on CI)
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATCH = os.path.join(ROOT, "patch", "vllm-moet-v0.24.0.patch")
LIST = os.path.join(ROOT, "patch", "FILES.txt")
SOURCE = os.path.join(ROOT, "patch", "SOURCE.txt")

BRANCH = "moet-v0.24.0"
BASE_TAG = "v0.24.0"
FORK_CANDIDATES = ["/workspace/vllm-v0.24.0", "/root/workspace/vllm-v0.24.0"]

FILES_HEADER = """\
# Files touched by patch/vllm-moet-v0.24.0.patch (sorted; generated by
# tools/check_patch_files.py --update, verified by CI bench-lint).
# A file DISAPPEARING from this list means a line of work exists in the
# patch but not in the vllm fork branch the patch is generated from —
# merge it into the branch first; do not ship the regeneration.
"""

SOURCE_HEADER = """\
# The vllm fork-branch commit patch/vllm-moet-v0.24.0.patch was generated
# from (branch moet-v0.24.0, diffed against the v0.24.0 tag). Written by
# tools/check_patch_files.py --update, byte-verified wherever a fork
# clone is available (dev boxes; CI has none). Regenerations only move
# this FORWARD along the branch - see AGENTS.md. Never edit by hand.
"""

_SHA_RE = re.compile(r"^[0-9a-f]{40}$")
# `index <old>..<new>[ <mode>]` lines carry abbreviated blob hashes whose
# length depends on local git config (core.abbrev); normalize them away so
# the byte-compare tracks content, not config.
_INDEX_RE = re.compile(rb"^index [0-9a-f]+\.\.[0-9a-f]+( \d+)?$")


def git(repo: str, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", repo, *args],
                          capture_output=True, check=check)


def find_fork() -> str | None:
    env = os.environ.get("VLLM_MOET_FORK")
    candidates = [env] if env else FORK_CANDIDATES
    for cand in candidates:
        if not cand or not os.path.isdir(cand):
            continue
        if git(cand, "rev-parse", "--verify", "--quiet", BRANCH,
               check=False).returncode == 0:
            return cand
    return None


def patch_files() -> list[str]:
    files = set()
    with open(PATCH) as f:
        for line in f:
            m = re.match(r"^diff --git a/(\S+) b/(\S+)", line)
            if m:
                files.add(m.group(2))
    return sorted(files)


def listed_files() -> list[str]:
    if not os.path.exists(LIST):
        return []
    with open(LIST) as f:
        return sorted(l.strip() for l in f
                      if l.strip() and not l.startswith("#"))


def read_source() -> str | None:
    if not os.path.exists(SOURCE):
        return None
    with open(SOURCE) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                if not _SHA_RE.match(line):
                    sys.exit(f"patch/SOURCE.txt is malformed ({line!r} is "
                             "not a full sha) - regenerate via --update")
                return line
    return None


def normalized(diff: bytes) -> list[bytes]:
    return [b"index" if _INDEX_RE.match(l) else l for l in diff.split(b"\n")]


def check_files() -> int:
    actual = patch_files()
    expected = listed_files()
    missing = sorted(set(expected) - set(actual))
    extra = sorted(set(actual) - set(expected))
    if not missing and not extra:
        print(f"patch file list OK ({len(actual)} files)")
        return 0
    if missing:
        print("FILES IN FILES.txt BUT MISSING FROM THE PATCH — a line of "
              "work was dropped by a regeneration (merge it into the vllm "
              "fork branch, do not update the list to paper over it):")
        for f in missing:
            print(f"  - {f}")
    if extra:
        print("files in the patch but not in FILES.txt (new work — run "
              "--update and commit the list together with the patch):")
        for f in extra:
            print(f"  + {f}")
    return 1


def check_source(fork: str | None) -> int:
    sha = read_source()
    if sha is None:
        print("patch/SOURCE.txt missing - the patch has no recorded source "
              "commit; regenerate via --update (see AGENTS.md)")
        return 1
    if fork is None:
        print(f"patch source: no fork clone here - byte-verify skipped "
              f"(SOURCE.txt records {sha[:12]})")
        return 0
    if git(fork, "cat-file", "-e", sha + "^{commit}",
           check=False).returncode != 0:
        print(f"patch source: recorded commit {sha[:12]} is unknown in the "
              f"fork clone at {fork} - fetch the fork remotes and retry")
        return 1
    regen = git(fork, "diff", BASE_TAG, sha).stdout
    if normalized(regen) == normalized(open(PATCH, "rb").read()):
        print(f"patch source OK: byte-identical to "
              f"`git diff {BASE_TAG} {sha[:12]}` in {fork}")
        return 0
    print(f"THE PATCH IS NOT THE GENERATION OF ITS RECORDED SOURCE "
          f"({sha[:12]}): it was hand-edited, or regenerated outside "
          "--update. Work that exists only in the patch file must be "
          "merged into the fork branch FIRST, then regenerate with "
          "--update. Never hand-edit the patch (see AGENTS.md).")
    return 1


def check(fork: str | None) -> int:
    return check_files() | check_source(fork)


def update(fork: str | None) -> int:
    if fork is None:
        sys.exit("--update needs the vllm fork clone (branch "
                 f"{BRANCH}); set VLLM_MOET_FORK or clone to "
                 f"{FORK_CANDIDATES[0]}")
    # The local branch must contain everything already pushed: a regen from
    # a branch that lags the remote would drop other people's shipped work.
    remote_ref = "refs/remotes/fork/" + BRANCH
    if git(fork, "rev-parse", "--verify", "--quiet", remote_ref,
           check=False).returncode == 0:
        if git(fork, "merge-base", "--is-ancestor", remote_ref, BRANCH,
               check=False).returncode != 0:
            sys.exit(f"refusing: fork/{BRANCH} is not an ancestor of the "
                     f"local {BRANCH} - the local branch is missing pushed "
                     "commits; merge/pull in the fork clone first")
    new = git(fork, "rev-parse", BRANCH).stdout.decode().strip()
    old = read_source()
    if old and old != new:
        if git(fork, "cat-file", "-e", old + "^{commit}",
               check=False).returncode != 0:
            sys.exit(f"refusing: recorded source {old[:12]} is unknown in "
                     f"the fork clone - fetch the fork remotes first")
        if git(fork, "merge-base", "--is-ancestor", old, new,
               check=False).returncode != 0:
            sys.exit(f"refusing: recorded source {old[:12]} is NOT an "
                     f"ancestor of the {BRANCH} tip {new[:12]} - "
                     "regenerating would roll back work that already "
                     "shipped; merge the missing line into the branch "
                     "first (see AGENTS.md)")
    patch_was_dirty = git(ROOT, "diff", "--quiet", "--",
                          os.path.relpath(PATCH, ROOT),
                          check=False).returncode != 0
    diff = git(fork, "diff", BASE_TAG, new).stdout
    if b"diff --git" not in diff:
        sys.exit(f"refusing: `git diff {BASE_TAG} {BRANCH}` came back "
                 "empty - wrong clone or branch?")
    with open(PATCH, "wb") as f:
        f.write(diff)
    files = patch_files()
    with open(LIST, "w") as f:
        f.write(FILES_HEADER)
        f.write("\n".join(files) + "\n")
    with open(SOURCE, "w") as f:
        f.write(SOURCE_HEADER)
        f.write(new + "\n")
    if patch_was_dirty:
        print("note: patch/ had UNCOMMITTED edits and they were just "
              "overwritten by this regeneration - if that was a line of "
              "work, it must land on the fork branch, not in the patch")
    print(f"patch regenerated from {BRANCH} @ {new[:12]} "
          f"({len(files)} files)"
          + (f" [source {old[:12]} -> {new[:12]}]" if old else ""))
    print("now REVIEW `git diff patch/` (vanishing FILES.txt entries = "
          "someone's work is not on the branch) and commit the three "
          "patch/ files together")
    return check(fork)


def main() -> int:
    fork = find_fork()
    if "--update" in sys.argv:
        return update(fork)
    return check(fork)


if __name__ == "__main__":
    sys.exit(main())
